### PR TITLE
Fix for non-web apps

### PR DESCRIPTION
**Pull request by AmyJeanes**
The current version doesn't seem to work on console apps - only web apps. This one works on all of them.

### CODE REVIEW

**Comment by maximkornilov** [comment]
Thanks. I am going to check and merge the changes.

**Comment by AmyJeanes** [comment]
Thanks - also I recommend changing Remove to Delete in the install script for the temporary files - Remove only removes them from the project while Delete removes them from disk too, otherwise it interferes with source control and the temporary files get left over:

`{ $_.Remove() }` to `{ $_.Delete() }`

```
$project.ProjectItems | where {$_.Name -eq "MSBuild.WebApplication.CopyContentLinkedFiles.Dummy.txt"} | ForEach-Object { $_.Delete() }
```

Source: http://stackoverflow.com/questions/15432284/how-to-remove-and-delete-folder-from-project-in-nuget-powershell-install

**Comment by AmyJeanes** [comment]
Hi @maximkornilov, have you had a chance to try out these changes yet?

We've been using our modified version within our projects since this pull req was opened and it's been working great for us, both in web apps and console apps.

I'd love to see the changes officially in your NuGet package so we don't have to use our custom versions anymore.

**Comment by maximkornilov** [comment]
Hi, Matt. Sorry for delay. This week will ship new version of the package with your changes.

**Comment by AmyJeanes** [comment]
Great to hear.

**Comment by maximkornilov** [comment]
@MattJeanes, there is [beta](https://www.nuget.org/packages/MSBuild.WebApplication.CopyContentLinkedFiles/1.1.0-beta) version of the package which includes your changes. 

I am going to add some CI integration and tests. After this release will be published.

**Pull request merged**
